name: config_reader
description: A new Flutter module.
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http:
  xml:
  color:
  image:
  process_run:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
